name: 'books_project'
version: '1.0.0'
config-version: 2
profile: 'books_project' 

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  books_project: # this must match the profile name
    staging:
      +materialized: table
      +tags: ['staging']
    intermediate:
      +materialized: table
      +tags: ['intermediate']
    marts:
      +materialized: table
      +tags: ['marts']

vars:
  processing_date: '{{ run_started_at.strftime("%Y-%m-%d") }}'